# Producto escalar

En este capítulo estaremos considerando espacios vectoriales reales y complejos, por lo tanto cada vez que se mencione un cuerpo se estará haciendo referencia al cuerpo de los números reales, $\mathbb{R}$, o al cuerpo de los números complejos, $\mathbf{C}$. Y se hará una abstracción de lo que en el capítulo 2 se presentó como el producto punto entre vectores.

```{definition}
Sea $\mathbb{F}$ un cuerpo ($\mathbb{R}$ o $\mathbf{C}$), y $V$ un espacio vectorial sobre $\mathbb{F}$. Un *producto interno* (o *producto interior*) sobre $V$ es una operación binaria de $V\times V$ en $\mathbb{F}$, $(\alpha,\beta)\mapsto (\alpha|\beta)$ tal que para todo $\alpha,\beta,\gamma\in V$ y $c,d\in\mathbb{F}$:
[a] $(\alpha|\beta)=\bar{(\beta|\alpha)}$, donde la barra indica la conjugación compleja;
[b] $(c\alpha+d\beta|\gamma)=c(\alpha|\gamma)+d(\beta|\gamma)$ y
[c] $(\alpha|\alpha)>0$ si $\alpha\neq 0$.

En el caso que tal operación exista, decimos que $V$ es un *espacio vectorial con producto interno*.

```

```{remark}
De (a) y (b) se sigue que $(\alpha|c\beta+\gamma)=\bar{c}(\alpha|\beta)+(\alpha|\gamma)$.

```

```{example}
En el espacio vectorial $\mathbf{C}^{n}$, la operación $(\alpha|\beta)=\sum_{i=1}^{n} x_{i}\bar{y_{i}}$, donde $\alpha=(x_{1},x_{2},\cdots,x_{n})$ y $\beta=(y_{1},y_{2},\cdots,y_{n})$; es un producto interno, llamado el *producto interno canónico en* $\mathbf{C}^{n}$.
Por otro lado, si consideramos esta misma operación sobre $\mathbb{R}$, la conjugación queda sin efecto y así el *producto interno canónico en* $\mathbb{R}$ es la operación $(\alpha|\beta)=\sum_{i=1}^{n} x_{i}y_{i}$.

```

```{example,label=ejemplo84}
En $\mathbb{C}^{2}$ definimos la operación $((x,y)|(z,w))=2x\bar{z}+x\bar{w}+y\bar{z}+y\bar{w}$ es un producto interno.

```

```{example, label=ejemplo85}
Sea $V=\mathbb{F}^{n\times n}$, el espacio de todas las matrices $n\times n$ sobre $\mathbb{F}$. Entonces $V$ es isomorfo de forma natural al espacio $\mathbb{F}^{n^{2}}$, entonces se sigue: $$(A|B)=\sum_{i,j}A_{ij}\bar{B}_{ij}$$ define un producto interno sobre $V$. Si definimos $[B^{\ast}]_{kj}=\bar{B}_{jk}$, entonces $(A|B)=tr(AB^{\ast})=tr(B^{\ast}A)$. 

```

```{example, label=ejemplo86}
Sea $V$ el espacio vectorial de las funciones continuas de valores complejos definidas en el intervalo $[0,1]$. La operación $$(f|g)=\int_{0}^{1} f(t)\bar{g(t)}dt$$ es un producto interno en $V$. Para funciones a valores reales, la misma operación omitiendo el conjugado, es un producto interno sobre el espacio respectivo.

```

```{example}
Se pueden construír productos internos a partir de un producto interno dado. Sean $V$ y $W$ espacios vectoriales sobre $\mathbb{F}$. Sea $(|)$ es un producto interno en $W$. Sea $T$ una transformación lineal inyectiva de $V$ en $W$, entonces la operación $$p_{T}(\alpha|\beta)=(T\alpha|T\beta)$$ define un producto interno en $V$.

```

```{example}
Sea $\mathbb{F}^{n\times 1}$ el espacio de las matrices columnas $n\times 1$ sobre $\mathbb{F}$ y sea $P$ una matriz $n\times n$ invertible. Definimos la operación $$(A|B)=B^{\ast}P^{\ast}PA$$ para $A,B\in \mathbb{F}^{n\times 1}$. Si identificamos la matriz $1\times 1$ con el único elemento que la conforma, tenemos una operación de $\mathbb{F}^{n\times 1}\times \mathbb{F}^{n\times 1}$ en el campo $\mathbb{F}$ que resulta ser un producto interno. Note que si $P$ es la matriz unidad, entonces la operación es la misma (esencialmente) que la del ejemplo \@ref{ejemplo85}. También es un caso particular del ejemplo anterior.

```

```{example}
Sea $V$ un espacio vectorial de dimensión finita y sea $\mathcal{B}=\{\beta_{1},\beta_{2},\cdots,\beta_{n}\}$ una base ordenada de $V$. Sean $\epsilon_{1},\epsilon_{2},\cdots,\epsilon_{n}$ la base canónica en $\mathbb{F}^{n}$. Sea $T$ la transformación lineal de $V$ en $\mathbb{F}^{n}$ definida por $T\beta_{j}=\epsilon_{j}$, para cada $1\leq j\leq n$. Entonces $$p_{T}(\sum_{i=1}^{n}x_{i}\beta_{i}\sum_{j=1}^{n}y_{j}\beta_{j})=\sum_{i=1}^{n} x_{i}\bar{y_{i}}$$ es un producto interno en vista del ejemplo anterior. De este modo, para cada base de $V$, existe un producto interno sobre $V$ con la propiedad $(\beta_{i}|\beta_{j})=\delta_{ij}$.

```

```{example}
Sea $V$ el espacio de las funciones continuas en el intervalo $[0,1]$ y $W=V$. Sean $T$ el operador $(Tf)(t)=tf(t)$ para $0\leq t\leq 1$. Es fácil ver que $T$ es lineal, además que $T$ es no singular, en efecto, $Tf=0$ si y solo si $tf(t)=0$ para todo $0\leq t\leq 1$, si y solo si $f(t)=0$ para todo $0< t\leq 1$. Pero en $t=0$, como $f$ es continua, $f(0)=0$. Usando el producto interno del ejemplo \@ref{exp=ejemplo86}, se define el producto interno $$p_{T}(f,g)=\int_{0}^{1} (Tf)(t)\bar{(Tg)(t)}dt=\int_{0}^{1} t^{2}f(t)\overline{g(t)}dt.$$

```
Veamos algunos hechos generales sobre el producto interno. Supongamos que $V$ es un espacio vectorial complejo con producto interno. Sean $\alpha$ y $\beta$ vectores cualesquiera en $V$, entonces $$(\alpha|\beta)=Re(\alpha|\beta)+iIm(\alpha|\beta)$$
 donde $Re(\alpha|\beta)$ y $Im(\alpha|\beta)$ representan la parte real y la parte imaginaria del número $(\alpha|\beta)$, respectivamente. Como para todo número complejo $z$, $Im(z)=Re(-iz)$, se tiene que $Im(\alpha|\beta)=Re(-i(\alpha|\beta))$, por las propiedades del producto interno tenemos que $Im(\alpha|\beta)=Re(\alpha|i\beta))$. Luego, el producto interno se expresa en términos de la parte real de los números $(\alpha|\beta)$ $(\alpha|i\beta)$, esto es $$(\alpha|\beta)=Re(\alpha|\beta)+Re(\alpha|i\beta).$$
 También es útil expresar el producto interno en términos de la forma cuadrática. Definimos $||\alpha||:=\sqrt{(\alpha|\alpha)}$, la *función norma* de $\alpha$. Esta función es la que en los espacios $\mathbb{R}$ y $\mathbf{C}$ conocemos como longitud de un vector. La *forma cuadrática* determinada por el producto interno es la función $\alpha\mapsto||\alpha||^{2}$. De las propiedades del producto interno, se tiene que 
 $$||\alpha\pm\beta||^{2}=||\alpha||^{2}\pm 2Re(\alpha|\beta)+||\beta||^{2}.$$
 En el caso que real
 $$(\alpha|\beta)=\frac{1}{4}||\alpha+\beta||-\frac{1}{4}||\alpha-\beta||$$
 y en el caso complejo, sabiendo que $(\alpha|\beta)=Re(\alpha|\beta)+Re(\alpha|i\beta)$, tenemos que
 $$\begin{array}{rl}
 (\alpha|\beta)=&\frac{1}{4}||\alpha+\beta||-\frac{1}{4}||\alpha-\beta||+\frac{i}{4}||\alpha+i\beta||-\frac{i}{4}||\alpha-i\beta||\\
 =&\frac{1}{4}\sum_{n=1}^{4}i^{n}||\alpha+i^{n}\beta||^{2}
 \end{array}.$$
 Estas últimas dos igualdades se conocen con el nombre de *identidades de polarización.
 Note que las propiedades anteriores son válidas para todo espacio $V$ (real o complejo) independientemente de su dimensión. En el caso de espacios de dimensión finita, se puede representar el producto interno en términos de una base ordenada del espacio.
 Sea $V$ es un espacio de dimensión finita y $\mathcal{B}=\{\alpha_{1},\cdots, \alpha_{n}\}$ una base de $V$. Supongamos que $\alpha=\sum_{k} x_{k}\alpha_{k}$ y $\beta=\sum_{j} y_{j}\beta_{j}$. entonces
 $$\begin{array}{rl}
 (\alpha|\beta)=&(\sum_{k} x_{k}\alpha_{k}|\beta)\\
 =&\sum_{k} x_{k}(\alpha_{k}|\beta)\\
 =&\sum_{k} x_{k}\sum_{j}\bar{y_{j}}(\alpha_{k}|\alpha_{j})\\
 =&\sum_{k,j} \bar{y_{j}}(\alpha_{k}|\alpha_{j})x_{k}
 \end{array}$$
 si llamamos $G$ a la matriz de los productos internos $(\alpha_{k}|\alpha_{j})$, esto es $G_{jk}=(\alpha_{k}|\alpha_{j})$ y $X$ y $Y$ a las matrices de coordenadas de los vectores $\alpha$ y $\beta$ en la base ordenada $\mathcal{B}$, nos queda 
 $$\begin{array}{rl}
 (\alpha|\beta)=&\sum_{k,j} \bar{y_{j}}(\alpha_{k}|\alpha_{j})x_{k}\\
 =&\sum_{k,j} Y^{\ast}GX
 \end{array}$$
 Diremos que $G$ es la *matriz del producto interno en la base ordenada. Esta matriz es hermítica, esto es $G^{\ast}=G$, que además satisface que 
 ```{equation,label:ec81}
 X^{\ast}GX>0
 
 ```
 
 siempre que $X\neq 0$. Además, $G$ es invertible; en efecto, si $G$ no es invertible, existe $X\neq 0$ tal que $GX=0$ y as\'i $X^{\ast}GX=0$, lo que es una contradicción. Interpretando \@ref{eq=ec81}, nos dice que existen escalares $x_{1},\cdots,x_{n}$ no todos nulos, tales que $$\sum_{k,j} \bar{x_{j}}G_{jk}x_{k}>0$$
 Esto último implica que los elementos de la diagonal de $G$ son positivos.
 De forma recíproca, si $G$ es una matriz $n\times n$ sobre $\mathbb{F}$ que satisface \@ref{eq=ec81} y la condición $G^{\ast}=G$, entonces existe una función producto interno en $V$ y una base ordenada $\mathcal{B}$ tal que $G$ es la matriz del producto interno en la base $\mathcal{B}$. Más específicamente, la función dada por $(\alpha|\beta)=Y^{\ast}GX$ donde $X$ e $Y$ son las matrices de coordenadas de $\alpha$ y $\beta$ en la base $\mathcal{B}$.
 
```{definition}
 Un espacio $V$ con un producto interno definido sobre él, lo llamaremos *espacio (con) producto interno*. Un espacio producto interno real de dimensión finita, se suele llamar *espacio euclideano*. Llamaremos *espacio unitario* a los espacios producto interno complejos.

```

```{theorem}
Sea $V$ un espacio producto interno. Entonces para cuales quiera vectores $\alpha$, $\beta\in V$ y todo escalar $c$, se cumple que:
(i.) $||c\alpha||=|c|\,||\alpha||$,
(ii.) Si $\alpha\neq 0$, $||\alpha||>0$,
(iii.) $|(\alpha|\beta)|\leq ||\alpha||\,||\beta||$,
(iv.) $||\alpha+\beta||\leq||\alpha||+||\beta||$.

```

```{proof}
Tanto (i.) como (ii.) se siguen fácilmente de las definiciones de producto interno y norma.
Si $\alpha=0$, (iii.) se cumple. Supongamos que $\alpha\neq 0$. Sea $\gamma=\beta-\frac{(\beta|\alpha)}{||\alpha||^{2}} \alpha$. Entonces $(\gamma|\alpha)=0$, así
$$\begin{array}{rrl}
	0\leq&||\gamma||^{2}=&\left(\beta-\dfrac{(\beta|\alpha)}{||\alpha||^{2}} \left|  \beta-\dfrac{(\beta|\alpha)}{||\alpha||^{2}} \right.  \right)\\
		&=&(\beta|\beta)-\dfrac{(\beta|\alpha)(\alpha|\beta)}{\| \alpha \|^{2}}\\
		&=&\|\beta\|^{2}-\dfrac{|(\alpha|\beta)|^{2}}{\|\alpha\|^{2}}
	\end{array}$$
de donde se tiene que $|(\alpha|\beta)|^{2}=\|\alpha\|^{2}\|\beta\|^{2}$.
Ahora, ya habíamos visto que 
$$\begin{array}{rl}
	\|\alpha+\beta\|^{2}=&\|\alpha\|^{2}+2Re(\alpha|\beta)+\|\beta\|^{2}\\
	\leq&\|\alpha\|^{2}+2\|\alpha\|\|\beta\|+\|\beta\|^{2}\\
	=&(\|\alpha\|+\|\beta\|)^{2}
	\end{array}$$ luego $\|\alpha+\beta\|\leq \|\alpha\|+\|\beta\|$.

```

La desigualdad (iii.) del teorema anterior se llama *desigualdad de Cauchy-Schwarz*. De la demostración se puede ver que la igualdad en (iii.) se tiene si y solo si los vectores $\alpha$ y $\beta$ son linealmente dependientes.

```{example}
Aplicando la desigualdad de Cauchy-Schwarz al producto interno canónico se obteiren $$|\sum x_{j}\bar{y_{j}}|\leq \left( \sum |x_{j}|^{2} \right)^{\frac{1}{2}} \left( \sum |y_{j}|^{2} \right)^{\frac{1}{2}} $$

```

###Ejercicios
[1] Sea $(|)$ un producto interno sobre el espacio vectorial $V$. Demuestre que:
		(a) $(0|\beta)=0$ para todo vector $\beta\in V$.
 		(b) Si $(\alpha|\beta)=0$ para todo $\beta\in V$, entonces $\alpha=0$.

Respuesta: (a) De las propiedades del producto interno, se tiene que $(0|\beta)=(\alpha-\alpha|\beta)=(\alpha|\beta)-(\alpha|\beta)$ para cualquier $\beta\in V$. (b) Se sigue de la última condición de la definición de producto interno.

[2] Sea $V$ un espacio vectorial sobre el cuerpo $\mathbb{F}$. Muestre que la suma  y los múltiplos positivos de productos internos sobre $V$, es un producto interno sobre $V$.

Respuesta: (a) Sean $(|)$ y $[|]$ dos productos internos sobre $V$. Sea $p(\alpha,\beta)=(\alpha|\beta)+[\alpha|\beta]$. Veamos que $p$ es un producto interno: 
[i.] $\begin{array}{rl}
p(c\alpha+\gamma|\beta)=&(c\alpha+\gamma|\beta)+[c\alpha+\gamma|\beta]\\
=&c(\alpha|\beta)+c[\alpha|\beta]+(\gamma|\beta)+[\gamma|\beta]\\
=&cp(\alpha,\beta)+p(\gamma,\beta)
\end{array},$
[ii.] $p(\beta,\alpha)=(\beta|\alpha)+[\beta|\alpha]=\overline{(\alpha|\beta)}+\overline{[\alpha|\beta]}=\overline{(\beta|\alpha)+[\beta|\alpha]}=\overline{p(\beta,\alpha)}$,
[iii.] Supongamos que $\alpha\neq 0$, $p(\alpha,\alpha)=(\alpha|\alpha)+[\alpha|\alpha]>0$.
(b) Sea $k\in\mathbb{F}$ un escalar positivo, veamos que $k(|)$ es un producto interno. 
[i.] $$\begin{array}{rl}
 k(c\alpha+\gamma|\beta)=&k(c\alpha+\gamma|\beta)\\
 =&k(c(\alpha|\beta)+(\gamma|\beta))\\
 =&ck(\alpha,\beta)+k(\gamma,\beta)
 \end{array},$$
 [ii.] $k(\beta,\alpha)=k\overline{(\alpha|\beta)}=\overline{k(\beta|\alpha)}$,
 [iii.] Supongamos que $\alpha\neq 0$, $k(\alpha,\alpha)>0$ ya que $(\alpha,\alpha)>0$.

[3.] Demuestre que el producto interno canónico sobre $\mathbb{F}^{n}$, es un producto interno.
 Respuesta: Veamos que $(\alpha|\beta)=\sum_{j}x_{j}\bar{y}_{j}$ es un producto interno. Sean $\alpha$, $\beta$ y $\gamma$ vectores de $\mathbb{F}^{n}$; supongamos que $\alpha=(x_{1},\cdots,x_{n})$, $\beta=(y_{1},\cdots,y_{n})$ y $\gamma=(z_{1},\cdots,z_{n})$. Entonces:
[i.] $$\begin{array}{rl}
 		(c\alpha+\gamma|\beta)=&\sum_{j}(cx_{j}+z_{j})\bar{y}_{j}\\
 		=&\sum_{j}cx_{j}\bar{y}_{j}+z_{j}\bar{y}_{j}\\
 		=&c\sum_{j}x_{j}\bar{y}_{j}+\sum_{j}z_{j}\bar{y}_{j}\\
 		=&c(\alpha|\beta)+(\gamma|\beta)
 		\end{array},$$
[ii.] $$\begin{array}{rl}
 		(\beta|\alpha)=&\sum_{j}(y_{j})\bar{x}_{j}\\
 		=&\overline{\sum_{j}\bar{y}_{j}{x}_{j}}\\
 		=&\overline{(\alpha|\beta)}
 		\end{array},$$
[iii.] Supongamos que $\alpha\neq 0$, $(\alpha|\alpha)=\sum_{j}x_{j}\bar{x}_{j}=\sum_{j} |x_{j}|^{2}>0$.

[4.] Describa la desigualdad de Cauchy-Schwarz para los productos internos definidos en los ejemplos \ref{ej85} y \ref{ej86}.

 Respuesta: Para el ejemplo \ref{ej85}, la desigualdad de Cauchy-Schwarz es: $$|tr(AB^{\ast})|\leq (tr(AA^{\ast}))^{\frac{1}{2}}(tr(BB^{\ast}))^{\frac{1}{2}}$$
 y en el ejemplo \ref{ej86}, la desigualdad de Cauchy-Schwarz quedaría expresada como:
 	$$\left|\int_{0}^{1} f(x)\overline{g(x)} dx\right|\leq \left( \int_{0}^{1} |f(x)|^{2} dx\right)^{2}  \left(\int_{0}^{1} |g(x)|^{2} dx\right)^{2}$$